// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRWdoA1sk1_zAXbVXcehQLToAPX1cXo40',
    appId: '1:289560861829:android:4d5a84a09c97f45eb11dec',
    messagingSenderId: '289560861829',
    projectId: 'flutter-social-media-app-a3ef4',
    storageBucket: 'flutter-social-media-app-a3ef4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKEXuv6hKkxkkw97JljXV_e3qsvMJ0Emo',
    appId: '1:289560861829:ios:6e8cc405f82a3f73b11dec',
    messagingSenderId: '289560861829',
    projectId: 'flutter-social-media-app-a3ef4',
    storageBucket: 'flutter-social-media-app-a3ef4.appspot.com',
    iosClientId: '289560861829-serfe5c7lrha68c8v7boeqs1dv0s036c.apps.googleusercontent.com',
    iosBundleId: 'com.lianglliu.flutterSocialMediaApp',
  );
}
